# Generated by Django 4.2.7 on 2023-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=100)),
                ('Esal', models.IntegerField()),
                ('Ejob', models.CharField(max_length=100)),
            ],
        ),
    ]
